package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// change_config.go adds PR change types that edit whole config/app files
// (platform/policies/catalogs/access, storage class, per-app storage) and a
// live PR-status refresh. The UI posts the full new file content (it shows the
// current file, the user edits, we open a PR). Durable change = PR only.

// createFileEditPR validates the path and opens a PR replacing one file.
func createFileEditPR(r *http.Request, typ, path, content, reason string) (changeRecord, error) {
	if !relPathOK(path) {
		return changeRecord{}, fmt.Errorf("path not allowed: %s", path)
	}
	if strings.TrimSpace(content) == "" {
		return changeRecord{}, fmt.Errorf("empty content")
	}
	if strings.HasSuffix(path, ".json") {
		var probe any
		if json.Unmarshal([]byte(content), &probe) != nil {
			return changeRecord{}, fmt.Errorf("invalid JSON for %s", path)
		}
	}
	files := []generatedFile{{Path: path, Content: content}}
	title := typ + ": edit " + path
	body := "Generated by homelab control-api.\n\nReason: " + reason + "\n"
	branch := branchName(strings.ReplaceAll(typ, ".", "-"), "edit")
	return createPRChange(r, typ, title, body, branch, files)
}

func fileEditHandler(typ, path, minRole string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "POST only", http.StatusMethodNotAllowed)
			return
		}
		if !requireRole(w, r, minRole) {
			return
		}
		var req struct {
			Content string `json:"content"`
			Reason  string `json:"reason"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad json"})
			return
		}
		rec, err := createFileEditPR(r, typ, path, req.Content, req.Reason)
		if err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error(), "change_id": rec.ID})
			return
		}
		writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "branch": rec.Branch, "pr": prResult{Number: rec.PRNumber, URL: rec.PRURL}})
	}
}

var platformConfigChangeHandler = fileEditHandler("platform.config", "config/platform.nix", "admin")
var policyConfigChangeHandler = fileEditHandler("policy.config", "config/policies.nix", "admin")

// --- structured Nix generation (catalog add, storage class) ----------------
//
// These used to be whole-file replaces where the WEB DIALOG interpolated user
// input into Nix (insufficient escaping = Nix injection). The server is the
// security boundary, so it now builds the entry itself: atoms go through
// strict allowlist regexes, free text through nixString (escapes \ " $), and
// the entry is spliced into the existing block by index (never regexp
// replacement, so escaped '$'/'\' can't act as metacharacters).

// reCatalogID lives in library.go (shared with /v1/library).
var reCatalogRef = regexp.MustCompile(`^[A-Za-z0-9._/-]{1,100}$`)
var reStorageClassName = regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_-]{0,39}$`)
var reCatalogsBlock = regexp.MustCompile(`(?s)(catalogs = \[\n)(.*?)(\n[ \t]*\];)`)
var reStorageClassesBlock = regexp.MustCompile(`(?s)(storageClasses = \{\n)(.*?)(\n[ \t]*\};)`)

// nixSafeText reports whether free text may be embedded (via nixString) on a
// single line of generated Nix: bounded length, no control characters.
func nixSafeText(s string, max int) bool {
	if len(s) > max {
		return false
	}
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return false
		}
	}
	return true
}

// spliceIntoNixBlock inserts entry as the last element of the list/attrset
// matched by block (open, body, close groups). Index splice, not ReplaceAll.
func spliceIntoNixBlock(content string, block *regexp.Regexp, entry string) (string, bool) {
	m := block.FindStringSubmatchIndex(content)
	if m == nil {
		return "", false
	}
	end := m[5] // end of the body group
	return content[:end] + "\n" + entry + content[end:], true
}

type catalogAddRequest struct {
	ID          string `json:"id"`
	Repo        string `json:"repo"`
	Ref         string `json:"ref"`
	Trust       string `json:"trust"`
	Policy      string `json:"policy"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Category    string `json:"category"`
	Reason      string `json:"reason"`
	Content     string `json:"content"` // legacy raw whole-file replace (Settings editor)
}

// buildCatalogEntry generates one config/catalogs.nix list entry from
// validated fields. Pure (unit-tested against injection payloads).
func buildCatalogEntry(req catalogAddRequest) (string, error) {
	if !reCatalogID.MatchString(req.ID) {
		return "", fmt.Errorf("bad catalog id (want [a-z0-9-], alnum start)")
	}
	if !strings.HasPrefix(req.Repo, "https://") || !validNixAtom(req.Repo) || strings.ContainsAny(req.Repo, " \t'") {
		return "", fmt.Errorf("repo must be a plain https:// URL")
	}
	if !reCatalogRef.MatchString(req.Ref) {
		return "", fmt.Errorf("bad ref (tag or commit SHA)")
	}
	switch req.Trust {
	case "official", "community", "untrusted":
	default:
		return "", fmt.Errorf("trust must be official|community|untrusted")
	}
	switch req.Policy {
	case "strict", "warn":
	default:
		return "", fmt.Errorf("policy must be strict|warn")
	}
	switch req.Category {
	case "", "media", "network", "dev", "data", "monitoring", "misc":
	default:
		return "", fmt.Errorf("bad category")
	}
	if !nixSafeText(req.Name, 80) || !nixSafeText(req.Description, 200) {
		return "", fmt.Errorf("name/description too long or has control characters")
	}
	lines := []string{
		"      id = " + nixString(req.ID) + ";",
		"      repo = " + nixString(req.Repo) + ";",
		"      ref = " + nixString(req.Ref) + ";",
		"      trust = " + nixString(req.Trust) + ";",
		"      policy = " + nixString(req.Policy) + ";",
	}
	if req.Name != "" {
		lines = append(lines, "      name = "+nixString(req.Name)+";")
	}
	if req.Description != "" {
		lines = append(lines, "      description = "+nixString(req.Description)+";")
	}
	if req.Category != "" {
		lines = append(lines, "      category = "+nixString(req.Category)+";")
	}
	return "    {\n" + strings.Join(lines, "\n") + "\n    }", nil
}

// catalogAddChangeHandler is now STRUCTURED: the dialog posts fields, the
// server generates and splices the Nix. The legacy whole-file content mode is
// kept for the Settings raw editor (admin — same trust as platform-config).
func catalogAddChangeHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "admin") {
		return
	}
	var req catalogAddRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad json"})
		return
	}
	if req.ID == "" && req.Content != "" {
		rec, err := createFileEditPR(r, "catalog.config", "config/catalogs.nix", req.Content, req.Reason)
		if err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error(), "change_id": rec.ID})
			return
		}
		writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "branch": rec.Branch, "pr": prResult{Number: rec.PRNumber, URL: rec.PRURL}})
		return
	}
	entry, err := buildCatalogEntry(req)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	b, err := os.ReadFile(filepath.Join(sourceDir(), "config", "catalogs.nix"))
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": "cannot read config/catalogs.nix"})
		return
	}
	content := string(b)
	m := reCatalogsBlock.FindStringSubmatch(content)
	if m == nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "catalogs block not found (non-standard file — edit config/catalogs.nix directly)"})
		return
	}
	if regexp.MustCompile(`(?m)^\s*id\s*=\s*"` + regexp.QuoteMeta(req.ID) + `"`).MatchString(m[2]) {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "catalog already exists: " + req.ID})
		return
	}
	next, _ := spliceIntoNixBlock(content, reCatalogsBlock, entry)
	reason := req.Reason
	if reason == "" {
		reason = "add catalog " + req.ID
	}
	rec, err := createFileEditPR(r, "catalog.config", "config/catalogs.nix", next, reason)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error(), "change_id": rec.ID})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "branch": rec.Branch, "pr": prResult{Number: rec.PRNumber, URL: rec.PRURL}})
}

var reCatalogEntryBlock = regexp.MustCompile(`(?s)    \{\n.*?\n    \}`)

// replaceCatalogEntry replaces (or removes, when remove=true) the catalogs.nix
// list entry whose id matches. Returns the new file content, or an HTTP status
// + error when the block or the entry cannot be located. Pure (unit-tested).
func replaceCatalogEntry(content, id, entry string, remove bool) (string, int, error) {
	m := reCatalogsBlock.FindStringSubmatchIndex(content)
	if m == nil {
		return "", http.StatusBadRequest, fmt.Errorf("catalogs block not found (non-standard file — edit config/catalogs.nix directly)")
	}
	body := content[m[4]:m[5]]
	blockStart, blockEnd := -1, -1
	for _, loc := range reCatalogEntryBlock.FindAllStringIndex(body, -1) {
		if strings.Contains(body[loc[0]:loc[1]], `id = "`+id+`"`) {
			blockStart, blockEnd = loc[0], loc[1]
			break
		}
	}
	if blockStart < 0 {
		return "", http.StatusNotFound, fmt.Errorf("catalog not found: %s", id)
	}
	var newBody string
	if remove {
		// Drop the separator newline the deleted entry leaves behind.
		newBody = strings.Trim(body[:blockStart]+body[blockEnd:], "\n")
	} else {
		newBody = body[:blockStart] + entry + body[blockEnd:]
	}
	return content[:m[4]] + newBody + content[m[5]:], http.StatusOK, nil
}

// mutateCatalogEntry updates or removes the catalogs.nix list entry whose id
// matches req.ID, then opens a PR with the new file. Shared by
// /v1/changes/catalog-update and /v1/changes/catalog-remove.
func mutateCatalogEntry(w http.ResponseWriter, r *http.Request, remove bool) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "admin") {
		return
	}
	var req catalogAddRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad json"})
		return
	}
	if !reCatalogID.MatchString(req.ID) {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad catalog id"})
		return
	}
	b, err := os.ReadFile(filepath.Join(sourceDir(), "config", "catalogs.nix"))
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": "cannot read config/catalogs.nix"})
		return
	}
	verb := "update"
	entry := ""
	if remove {
		verb = "remove"
	} else {
		e, err := buildCatalogEntry(req)
		if err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error()})
			return
		}
		entry = e
	}
	next, status, err := replaceCatalogEntry(string(b), req.ID, entry, remove)
	if err != nil {
		writeJSON(w, status, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	reason := req.Reason
	if reason == "" {
		reason = verb + " catalog " + req.ID
	}
	rec, err := createFileEditPR(r, "catalog.config", "config/catalogs.nix", next, reason)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error(), "change_id": rec.ID})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "branch": rec.Branch, "pr": prResult{Number: rec.PRNumber, URL: rec.PRURL}})
}

func catalogUpdateChangeHandler(w http.ResponseWriter, r *http.Request) {
	mutateCatalogEntry(w, r, false)
}

func catalogRemoveChangeHandler(w http.ResponseWriter, r *http.Request) {
	mutateCatalogEntry(w, r, true)
}

var reRoleName = regexp.MustCompile(`^(viewer|operator|maintainer|admin)$`)
var reIdentity = regexp.MustCompile(`^[^\s"]{1,120}$`)

// accessRoleChangeHandler is a STRUCTURED editor for config/access.json: it
// grants/revokes a user's role without the operator hand-editing JSON. It reads
// the current file, mutates the users map, and opens a PR with the new content.
func accessRoleChangeHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "admin") {
		return
	}
	var req struct {
		User   string `json:"user"`
		Role   string `json:"role"`
		Remove bool   `json:"remove"`
		Reason string `json:"reason"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad json"})
		return
	}
	if !reIdentity.MatchString(req.User) {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad user identity"})
		return
	}
	if !req.Remove && !reRoleName.MatchString(req.Role) {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "role must be viewer|operator|maintainer|admin"})
		return
	}

	// Load current access.json (ordered keys preserved via a generic map is
	// fine here — the file is small and re-serialized deterministically).
	var cfg struct {
		DefaultRole string            `json:"default_role"`
		Users       map[string]string `json:"users"`
		Roles       map[string]int    `json:"roles"`
	}
	if b, err := os.ReadFile(filepath.Join(sourceDir(), "config", "access.json")); err == nil {
		_ = json.Unmarshal(b, &cfg)
	}
	if cfg.Users == nil {
		cfg.Users = map[string]string{}
	}
	if cfg.DefaultRole == "" {
		cfg.DefaultRole = "viewer"
	}
	if cfg.Roles == nil {
		cfg.Roles = map[string]int{"viewer": 0, "operator": 1, "maintainer": 2, "admin": 3}
	}
	if req.Remove {
		delete(cfg.Users, req.User)
	} else {
		cfg.Users[req.User] = req.Role
	}

	content, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	rec, err := createFileEditPR(r, "access.role", "config/access.json", string(content)+"\n", req.Reason)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error(), "change_id": rec.ID})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "branch": rec.Branch, "pr": prResult{Number: rec.PRNumber, URL: rec.PRURL}})
}

type storageClassRequest struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	BasePath   string `json:"base_path"`
	BackedUp   bool   `json:"backed_up"`
	Ephemeral  bool   `json:"ephemeral"`
	BackupRepo string `json:"backup_repo"`
	Reason     string `json:"reason"`
	Content    string `json:"content"` // rejected — kept so old clients get a clear error
}

// buildStorageClassEntry generates one storageClasses attrset line from
// validated fields. Pure (unit-tested against injection payloads).
func buildStorageClassEntry(req storageClassRequest) (string, error) {
	if !reStorageClassName.MatchString(req.Name) {
		return "", fmt.Errorf("bad class name (letter/underscore start, then [a-zA-Z0-9_-], max 40)")
	}
	switch req.Type {
	case "local", "nfs", "ssd", "tmpfs":
	default:
		return "", fmt.Errorf("type must be local|nfs|ssd|tmpfs")
	}
	if !strings.HasPrefix(req.BasePath, "/") || !nixSafeText(req.BasePath, 200) {
		return "", fmt.Errorf("basePath must be an absolute path without control characters")
	}
	if !nixSafeText(req.BackupRepo, 300) {
		return "", fmt.Errorf("backupRepo too long or has control characters")
	}
	entry := "    " + req.Name + " = { type = " + nixString(req.Type) + "; basePath = " + nixString(req.BasePath) + "; backedUp = " + fmt.Sprintf("%t", req.BackedUp) + ";"
	if req.Ephemeral {
		entry += " ephemeral = true;"
	}
	if req.BackedUp && req.BackupRepo != "" {
		entry += " backupRepo = " + nixString(req.BackupRepo) + ";"
	}
	return entry + " };", nil
}

// storageClassChangeHandler adds one storage class to config/platform.nix.
// STRUCTURED only: the old whole-file mode let a maintainer replace all of
// platform.nix (admin territory) and trusted client-generated Nix; now the
// server validates fields and generates the entry itself.
func storageClassChangeHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "maintainer") {
		return
	}
	var req storageClassRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad json"})
		return
	}
	if req.Content != "" {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "storage-class is structured (name/type/base_path...); edit platform.nix via /v1/changes/platform-config"})
		return
	}
	entry, err := buildStorageClassEntry(req)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	b, err := os.ReadFile(filepath.Join(sourceDir(), "config", "platform.nix"))
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": "cannot read config/platform.nix"})
		return
	}
	content := string(b)
	m := reStorageClassesBlock.FindStringSubmatch(content)
	if m == nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "storageClasses block not found (non-standard file — edit config/platform.nix directly)"})
		return
	}
	if regexp.MustCompile(`(?m)^[ \t]*` + regexp.QuoteMeta(req.Name) + `[ \t]*=`).MatchString(m[2]) {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "storage class already exists: " + req.Name})
		return
	}
	next, _ := spliceIntoNixBlock(content, reStorageClassesBlock, entry)
	reason := req.Reason
	if reason == "" {
		reason = "add storage class " + req.Name
	}
	rec, err := createFileEditPR(r, "storage.class", "config/platform.nix", next, reason)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error(), "change_id": rec.ID})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "branch": rec.Branch, "pr": prResult{Number: rec.PRNumber, URL: rec.PRURL}})
}

// removeStorageClassEntry deletes the `name = { ... };` line from the
// storageClasses block of platform.nix. Pure (unit-tested). Returns the new
// content, or an HTTP status + error when the block/entry cannot be located.
func removeStorageClassEntry(content, name string) (string, int, error) {
	m := reStorageClassesBlock.FindStringSubmatchIndex(content)
	if m == nil {
		return "", http.StatusBadRequest, fmt.Errorf("storageClasses block not found (non-standard file — edit config/platform.nix directly)")
	}
	body := content[m[4]:m[5]]
	lineRe := regexp.MustCompile(`(?m)^[ \t]*` + regexp.QuoteMeta(name) + `[ \t]*=.*;[ \t]*$`)
	loc := lineRe.FindStringIndex(body)
	if loc == nil {
		return "", http.StatusNotFound, fmt.Errorf("storage class not found: %s", name)
	}
	start, end := loc[0], loc[1]
	// Swallow one of the surrounding newlines so no blank line is left behind.
	if end < len(body) && body[end] == '\n' {
		end++
	} else if start > 0 && body[start-1] == '\n' {
		start--
	}
	return content[:m[4]] + body[:start] + body[end:] + content[m[5]:], http.StatusOK, nil
}

// storageClassRemoveHandler deletes one storage class from platform.nix via PR.
// Refuses the platform default class and any class still referenced by an app
// volume — removing those would break path resolution at the next deploy.
func storageClassRemoveHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "admin") {
		return
	}
	var req struct {
		Name   string `json:"name"`
		Reason string `json:"reason"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || !reStorageClassName.MatchString(req.Name) {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad storage class name"})
		return
	}
	b, err := os.ReadFile(filepath.Join(sourceDir(), "config", "platform.nix"))
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": "cannot read config/platform.nix"})
		return
	}
	content := string(b)
	if regexp.MustCompile(`defaultStorageClass[ \t]*=[ \t]*"` + regexp.QuoteMeta(req.Name) + `"`).MatchString(content) {
		writeJSON(w, http.StatusConflict, map[string]any{"ok": false, "error": "cannot remove the default storage class; change defaultStorageClass first"})
		return
	}
	if apps, _ := filepath.Glob(filepath.Join(sourceDir(), "apps", "*.nix")); apps != nil {
		for _, f := range apps {
			ab, err := os.ReadFile(f)
			if err == nil && strings.Contains(string(ab), `class = "`+req.Name+`"`) {
				writeJSON(w, http.StatusConflict, map[string]any{"ok": false, "error": "storage class in use by " + filepath.Base(f) + "; move its volumes first"})
				return
			}
		}
	}
	next, status, err := removeStorageClassEntry(content, req.Name)
	if err != nil {
		writeJSON(w, status, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	reason := req.Reason
	if reason == "" {
		reason = "remove storage class " + req.Name
	}
	rec, err := createFileEditPR(r, "storage.class", "config/platform.nix", next, reason)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error(), "change_id": rec.ID})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "branch": rec.Branch, "pr": prResult{Number: rec.PRNumber, URL: rec.PRURL}})
}

var reVolName = regexp.MustCompile(`^[a-zA-Z0-9_-]{1,40}$`)

// retargetVolumeClass changes the storage class of one named volume in a v2 app
// module, matching the `name = "VOL"; kind = "..."; class = "..."` shape the
// generator emits. Returns (newContent, oldClass, ok).
func retargetVolumeClass(content, volume, class string) (string, string, bool) {
	re := regexp.MustCompile(`(name = "` + regexp.QuoteMeta(volume) + `"; kind = "[^"]*"; class = ")([^"]*)(")`)
	m := re.FindStringSubmatch(content)
	if m == nil {
		return "", "", false
	}
	old := m[2]
	// Keep the $1/$3 capture-group refs but neutralize any '$' inside the
	// (allowlisted) class so it can't act as a replacement metachar.
	safeClass := strings.ReplaceAll(class, "$", "$$")
	return re.ReplaceAllString(content, `${1}`+safeClass+`${3}`), old, true
}

// appStorageChangeHandler is a STRUCTURED editor: it changes one volume's
// storage class in apps/<app>.nix without the operator hand-editing Nix.
func appStorageChangeHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "operator") {
		return
	}
	var req struct {
		App    string `json:"app"`
		Volume string `json:"volume"`
		Class  string `json:"class"`
		Reason string `json:"reason"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad json"})
		return
	}
	if !reNewAppName.MatchString(req.App) || !reVolName.MatchString(req.Volume) {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "bad app or volume"})
		return
	}
	if _, ok := loadPlatform().StorageClasses[req.Class]; !ok {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "unknown storage class"})
		return
	}
	b, err := os.ReadFile(filepath.Join(sourceDir(), "apps", req.App+".nix"))
	if err != nil {
		writeJSON(w, http.StatusNotFound, map[string]any{"ok": false, "error": "app not found"})
		return
	}
	next, old, ok := retargetVolumeClass(string(b), req.Volume, req.Class)
	if !ok {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "volume not found in app (or non-standard layout)"})
		return
	}
	reason := req.Reason
	if reason == "" {
		reason = fmt.Sprintf("storage: %s/%s %s -> %s", req.App, req.Volume, old, req.Class)
	}
	rec, err := createFileEditPR(r, "app.storage", "apps/"+req.App+".nix", next, reason)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error(), "change_id": rec.ID})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "branch": rec.Branch, "pr": prResult{Number: rec.PRNumber, URL: rec.PRURL}})
}

// configFileHandler returns the raw source of an editable config/app file so
// the Settings/Storage screens can prefill an editor. Read-only; secrets files
// are never served.
func configFileHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "GET only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "operator") {
		return
	}
	path := r.URL.Query().Get("path")
	if !relPathOK(path) || strings.HasPrefix(path, "secrets/") {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "path not allowed"})
		return
	}
	b, err := os.ReadFile(filepath.Join(sourceDir(), filepath.FromSlash(path)))
	if err != nil {
		writeJSON(w, http.StatusNotFound, map[string]any{"ok": false, "error": "not found"})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "path": path, "content": string(b)})
}

// prGitHubStatus fetches one PR's live status. The statusCheckRollup GraphQL
// field needs the Checks read permission, which some fine-grained tokens can't
// even select; when it fails, fall back to state/mergeable/review only, then
// synthesize the CI rollup from `gh run list --commit <head>` — workflow runs
// only need Actions: read. The synthesized entries mimic CheckRun nodes
// (name/conclusion/detailsUrl uppercased) so the UI maps them unchanged.
func prGitHubStatus(env []string, repoArg string, prNumber int) (gh any, warning, ghErr string) {
	res := commandRunner(env, "gh", "pr", "view", fmt.Sprint(prNumber), "--repo", repoArg, "--json", "state,mergeable,reviewDecision,statusCheckRollup")
	rollupWarning := ""
	if res.Err == nil {
		var pr map[string]any
		if err := json.Unmarshal([]byte(res.Output), &pr); err == nil {
			return pr, "", ""
		}
		rollupWarning = "statut CI illisible (sortie gh non parsable); repli sans rollup"
	}
	res = commandRunner(env, "gh", "pr", "view", fmt.Sprint(prNumber), "--repo", repoArg, "--json", "state,mergeable,reviewDecision,headRefOid")
	if res.Err != nil {
		return nil, "", strings.TrimSpace(res.Output)
	}
	var pr map[string]any
	if json.Unmarshal([]byte(res.Output), &pr) != nil {
		return nil, "", "unparseable gh pr view output"
	}
	head, _ := pr["headRefOid"].(string)
	if head != "" {
		runs := commandRunner(env, "gh", "run", "list", "--repo", repoArg, "--commit", head, "--json", "name,status,conclusion,url")
		var rl []struct {
			Name       string `json:"name"`
			Status     string `json:"status"`
			Conclusion string `json:"conclusion"`
			URL        string `json:"url"`
		}
		if runs.Err == nil && json.Unmarshal([]byte(runs.Output), &rl) == nil && len(rl) > 0 {
			rollup := make([]map[string]any, 0, len(rl))
			for _, r := range rl {
				rollup = append(rollup, map[string]any{
					"name":       r.Name,
					"status":     strings.ToUpper(r.Status),
					"conclusion": strings.ToUpper(r.Conclusion),
					"detailsUrl": r.URL,
				})
			}
			pr["statusCheckRollup"] = rollup
			return pr, rollupWarning, ""
		}
	}
	warning = "CI indisponible: le token n'a ni Checks read ni Actions read"
	if rollupWarning != "" {
		warning = rollupWarning
	}
	return pr, warning, ""
}

// changesRefreshHandler enriches local change records with live GitHub PR
// status (CI / mergeable / review) via the gh CLI.
func changesRefreshHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "operator") {
		return
	}
	token, err := readGitToken()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	env := gitEnv(changeRepoDir(), token)
	repoArg := ghRepoArg(repoRemoteURL(changeRepoDir()))

	out := []map[string]any{}
	for _, rec := range readChangeRecords(50) {
		entry := map[string]any{
			"id": rec.ID, "type": rec.Type, "title": rec.Title, "status": rec.Status,
			"pr_number": rec.PRNumber, "pr_url": rec.PRURL,
			// Carry the detail-panel fields so refreshing GitHub status does not
			// strip the per-change logs/metadata the UI shows on row expand.
			"time": rec.Time, "actor": rec.Actor, "branch": rec.Branch, "commit": rec.Commit,
			"files": rec.Files, "error": rec.Error, "compare_url": rec.CompareURL,
		}
		if rec.PRNumber > 0 {
			entry["github"], entry["github_warning"], entry["github_error"] = prGitHubStatus(env, repoArg, rec.PRNumber)
		}
		out = append(out, entry)
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "changes": out})
}

// changesRetryHandler retries PR creation for a change whose branch was pushed
// but whose pull request was never opened (token scope failure, transient gh
// error). The branch and commit already exist on the remote, so only the PR
// step is replayed: adopt an existing open PR for the branch if one appeared,
// otherwise create it.
func changesRetryHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "operator") {
		return
	}
	var req struct {
		ID string `json:"id"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.ID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "id required"})
		return
	}
	var rec *changeRecord
	for _, c := range readChangeRecords(200) {
		if c.ID == req.ID {
			cc := c
			rec = &cc
			break // records are newest-first; keep the latest entry for this ID
		}
	}
	if rec == nil {
		writeJSON(w, http.StatusNotFound, map[string]any{"ok": false, "error": "change not found"})
		return
	}
	if rec.Branch == "" {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "change has no pushed branch to retry"})
		return
	}
	token, err := readGitToken()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	env := gitEnv(changeRepoDir(), token)
	repoArg := ghRepoArg(repoRemoteURL(changeRepoDir()))

	// A change that already points at a PR is only retryable when that PR was
	// closed without merging — then a fresh PR is opened for the same branch.
	if rec.PRNumber > 0 {
		view := commandRunner(env, "gh", "pr", "view", fmt.Sprint(rec.PRNumber), "--repo", repoArg, "--json", "state,url")
		var pr struct {
			State string `json:"state"`
			URL   string `json:"url"`
		}
		if view.Err == nil && json.Unmarshal([]byte(view.Output), &pr) == nil {
			switch pr.State {
			case "OPEN":
				writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "pr": prResult{Number: rec.PRNumber, URL: rec.PRURL}})
				return
			case "MERGED":
				writeJSON(w, http.StatusConflict, map[string]any{"ok": false, "error": "PR #" + fmt.Sprint(rec.PRNumber) + " was merged; nothing to retry"})
				return
			}
			// CLOSED: fall through and recreate.
		}
	} else if rec.Status != "failed" && rec.Status != "pushed" {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "change is not in a retryable state: " + rec.Status})
		return
	}

	next := *rec
	next.Time = ""
	next.Error = ""
	next.CompareURL = ""
	next.PRNumber = 0
	next.PRURL = ""

	title := rec.Title
	if title == "" {
		title = rec.Branch
	}

	// Rebuild the branch on top of the current main from its recorded files, so
	// the branch always shares history with main and the PR is valid — even when
	// the old branch diverged (e.g. main's history was rewritten, leaving the
	// stale branch with "no history in common with main"). Source the old files
	// from the branch tip first, falling back to the recorded commit.
	if len(rec.Files) == 0 {
		writeJSON(w, http.StatusConflict, map[string]any{"ok": false, "error": "change records no files to replay; re-run the original change"})
		return
	}
	newCommit, err := rebuildChangeBranch(token, rec.Branch, title, rec.Files, rec.Branch, rec.Commit)
	if err != nil {
		writeJSON(w, http.StatusBadGateway, map[string]any{"ok": false, "error": "cannot rebuild branch onto main: " + err.Error()})
		return
	}
	next.Commit = newCommit

	// Adopt an open PR for the branch if one was created out of band.
	list := commandRunner(env, "gh", "pr", "list", "--repo", repoArg, "--head", rec.Branch, "--state", "open", "--json", "number,url")
	if list.Err == nil {
		var prs []prResult
		if json.Unmarshal([]byte(list.Output), &prs) == nil && len(prs) > 0 {
			next.PRNumber = prs[0].Number
			next.PRURL = prs[0].URL
		}
	}
	if next.PRNumber == 0 {
		pr := commandRunner(env, "gh", "pr", "create", "--repo", repoArg, "--base", "main", "--head", rec.Branch, "--title", title, "--body", "Retried PR creation for change "+rec.ID+".")
		if pr.Err != nil {
			next.Status = "pushed"
			next.Error = pr.Output
			next.CompareURL = compareURL(repoArg, rec.Branch)
			appendChangeRecord(r, next)
			writeJSON(w, http.StatusBadGateway, map[string]any{"ok": false, "error": strings.TrimSpace(pr.Output), "change_id": next.ID, "compare_url": next.CompareURL})
			return
		}
		next.PRURL = strings.TrimSpace(pr.Output)
		if m := rePRNumber.FindStringSubmatch(next.PRURL); len(m) == 2 {
			next.PRNumber, _ = strconv.Atoi(m[1])
		}
	}
	next.Status = "open"
	appendChangeRecord(r, next)
	appendAuditEvent(r, auditEvent{Op: rec.Type + ".retry", Kind: "change", Target: rec.Branch, Risk: "medium", Result: "created", Status: http.StatusOK, Commit: next.Commit, Message: next.PRURL})
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": next.ID, "branch": next.Branch, "pr": prResult{Number: next.PRNumber, URL: next.PRURL}})
}

// changesMergeHandler merges the open PR of a change. Merging lands the change
// on main, which triggers a deploy, so it needs the maintainer role. The merge
// is gated on GitHub's own mergeability (CI green + no blocking review): gh
// refuses a not-yet-mergeable PR and we surface that error.
func changesMergeHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "maintainer") {
		return
	}
	var req struct {
		ID string `json:"id"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.ID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "id required"})
		return
	}
	var rec *changeRecord
	for _, c := range readChangeRecords(200) {
		if c.ID == req.ID {
			cc := c
			rec = &cc
			break
		}
	}
	if rec == nil || rec.PRNumber == 0 {
		writeJSON(w, http.StatusNotFound, map[string]any{"ok": false, "error": "no open PR for this change"})
		return
	}
	token, err := readGitToken()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	env := gitEnv(changeRepoDir(), token)
	repoArg := ghRepoArg(repoRemoteURL(changeRepoDir()))
	// --squash keeps main history linear; --delete-branch cleans up the change
	// branch once it has landed.
	res := commandRunner(env, "gh", "pr", "merge", fmt.Sprint(rec.PRNumber), "--repo", repoArg, "--squash", "--delete-branch")
	if res.Err != nil {
		writeJSON(w, http.StatusBadGateway, map[string]any{"ok": false, "error": strings.TrimSpace(res.Output)})
		return
	}
	merged := *rec
	merged.Time = ""
	merged.Status = "merged"
	merged.Error = ""
	appendChangeRecord(r, merged)
	appendAuditEvent(r, auditEvent{Op: rec.Type + ".merge", Kind: "change", Target: rec.Branch, Risk: "high", Result: "merged", Status: http.StatusOK, Commit: rec.Commit, Message: rec.PRURL})
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "pr_number": rec.PRNumber})
}

// changesCloseHandler closes a change's PR without merging and deletes its
// branch. Operator role: closing discards work but never touches main.
func changesCloseHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	if !requireRole(w, r, "operator") {
		return
	}
	var req struct {
		ID string `json:"id"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.ID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "id required"})
		return
	}
	var rec *changeRecord
	for _, c := range readChangeRecords(200) {
		if c.ID == req.ID {
			cc := c
			rec = &cc
			break
		}
	}
	if rec == nil || rec.PRNumber == 0 {
		writeJSON(w, http.StatusNotFound, map[string]any{"ok": false, "error": "no open PR for this change"})
		return
	}
	token, err := readGitToken()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	env := gitEnv(changeRepoDir(), token)
	repoArg := ghRepoArg(repoRemoteURL(changeRepoDir()))
	res := commandRunner(env, "gh", "pr", "close", fmt.Sprint(rec.PRNumber), "--repo", repoArg, "--delete-branch")
	if res.Err != nil {
		writeJSON(w, http.StatusBadGateway, map[string]any{"ok": false, "error": strings.TrimSpace(res.Output)})
		return
	}
	closed := *rec
	closed.Time = ""
	closed.Status = "closed"
	closed.Error = ""
	appendChangeRecord(r, closed)
	appendAuditEvent(r, auditEvent{Op: rec.Type + ".close", Kind: "change", Target: rec.Branch, Risk: "low", Result: "closed", Status: http.StatusOK, Commit: rec.Commit, Message: rec.PRURL})
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "change_id": rec.ID, "pr_number": rec.PRNumber})
}
